In [1]:
# Import all the necessary things first
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

In [2]:
iris = load_iris()
test_idx = [0, 50,  100]

In [3]:
# Training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis = 0)

In [4]:
# Testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [5]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [6]:
print test_target

[0 1 2]


In [7]:
print clf.predict(test_data)

[0 1 2]


In [8]:
# Visualize the tree
type (iris.data)

numpy.ndarray

In [9]:
import pandas as pd
from pandas import DataFrame


In [21]:
data = pd.read_csv("Iris.csv")



In [11]:
data = pd.read_csv("Iris.csv")
data.loc[data[' class'].str.contains("setosa"), 'c'] = 1
data.loc[data[' class'].str.contains("versicolor"), 'c'] = 2
data.loc[data[' class'].str.contains("virginica"), 'c'] = 3
data[' class'] = data['c']
data.drop('c', axis=1, inplace=True)
data

sepal_length  sepal_width   petal_length   petal_width   class
0             5.1          3.5            1.4           0.2     1.0
1             4.9          3.0            1.4           0.2     1.0
2             4.7          3.2            1.3           0.2     1.0
3             4.6          3.1            1.5           0.2     1.0
4             5.0          3.6            1.4           0.2     1.0
5             5.4          3.9            1.7           0.4     1.0
6             4.6          3.4            1.4           0.3     1.0
7             5.0          3.4            1.5           0.2     1.0
8             4.4          2.9            1.4           0.2     1.0
9             4.9          3.1            1.5           0.1     1.0
10            5.4          3.7            1.5           0.2     1.0
11            4.8          3.4            1.6           0.2     1.0
12            4.8          3.0            1.4           0.1     1.0
13            4.3          3.0            1.1           0.1     1.0
14            5.8          4.0            1.2           0.2     1.0
15            5.7          4.4            1.5           0.4     1.0
16            5.4          3.9            1.3           0.4     1.0
17            5.1          3.5            1.4           0.3     1.0
18            5.7          3.8            1.7           0.3     1.0
19            5.1          3.8            1.5           0.3     1.0
20            5.4          3.4            1.7           0.2     1.0
21            5.1          3.7            1.5           0.4     1.0
22            4.6          3.6            1.0           0.2     1.0
23            5.1          3.3            1.7           0.5     1.0
24            4.8          3.4            1.9           0.2     1.0
25            5.0          3.0            1.6           0.2     1.0
26            5.0          3.4            1.6           0.4     1.0
27            5.2          3.5            1.5           0.2     1.0
28            5.2          3.4            1.4           0.2     1.0
29            4.7          3.2            1.6           0.2     1.0
..            ...          ...            ...           ...     ...
120           6.9          3.2            5.7           2.3     3.0
121           5.6          2.8            4.9           2.0     3.0
122           7.7          2.8            6.7           2.0     3.0
123           6.3          2.7            4.9           1.8     3.0
124           6.7          3.3            5.7           2.1     3.0
125           7.2          3.2            6.0           1.8     3.0
126           6.2          2.8            4.8           1.8     3.0
127           6.1          3.0            4.9           1.8     3.0
128           6.4          2.8            5.6           2.1     3.0
129           7.2          3.0            5.8           1.6     3.0
130           7.4          2.8            6.1           1.9     3.0
131           7.9          3.8            6.4           2.0     3.0
132           6.4          2.8            5.6           2.2     3.0
133           6.3          2.8            5.1           1.5     3.0
134           6.1          2.6            5.6           1.4     3.0
135           7.7          3.0            6.1           2.3     3.0
136           6.3          3.4            5.6           2.4     3.0
137           6.4          3.1            5.5           1.8     3.0
138           6.0          3.0            4.8           1.8     3.0
139           6.9          3.1            5.4           2.1     3.0
140           6.7          3.1            5.6           2.4     3.0
141           6.9          3.1            5.1           2.3     3.0
142           5.8          2.7            5.1           1.9     3.0
143           6.8          3.2            5.9           2.3     3.0
144           6.7          3.3            5.7           2.5     3.0
145           6.7          3.0            5.2           2.3     3.0
146           6.3          2.5            5.0           1.9  

In [12]:
train_data = data[['sepal_length','sepal_width', ' petal_length',' petal_width']]
test_data = data[[' class']]

In [13]:
r = test_data[' class']
test = r.as_matrix()

In [14]:
train = pd.DataFrame.as_matrix(train_data)


In [15]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(train, test) 


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [16]:
print(neigh.predict([[5.9, 3.0, 5.1, 1.8]]))

[ 3.]


In [17]:
data.iloc[9].values[0:4]

array([ 4.9,  3.1,  1.5,  0.1])

In [18]:
c1 = ["rr",0]

In [19]:
c1[1] = c1[1]+1
c1

['rr', 1]

sepal_length  sepal_width   petal_length   petal_width   class
0             5.1          3.5            1.4           0.2     1.0
1             4.9          3.0            1.4           0.2     1.0
2             4.7          3.2            1.3           0.2     1.0
3             4.6          3.1            1.5           0.2     1.0
4             5.0          3.6            1.4           0.2     1.0
5             5.4          3.9            1.7           0.4     1.0
6             4.6          3.4            1.4           0.3     1.0
7             5.0          3.4            1.5           0.2     1.0
8             4.4          2.9            1.4           0.2     1.0
9             4.9          3.1            1.5           0.1     1.0
10            5.4          3.7            1.5           0.2     1.0
11            4.8          3.4            1.6           0.2     1.0
12            4.8          3.0            1.4           0.1     1.0
13            4.3          3.0            1.1           0.1     1.0
14            5.8          4.0            1.2           0.2     1.0
15            5.7          4.4            1.5           0.4     1.0
16            5.4          3.9            1.3           0.4     1.0
17            5.1          3.5            1.4           0.3     1.0
18            5.7          3.8            1.7           0.3     1.0
19            5.1          3.8            1.5           0.3     1.0
20            5.4          3.4            1.7           0.2     1.0
21            5.1          3.7            1.5           0.4     1.0
22            4.6          3.6            1.0           0.2     1.0
23            5.1          3.3            1.7           0.5     1.0
24            4.8          3.4            1.9           0.2     1.0
25            5.0          3.0            1.6           0.2     1.0
26            5.0          3.4            1.6           0.4     1.0
27            5.2          3.5            1.5           0.2     1.0
28            5.2          3.4            1.4           0.2     1.0
29            4.7          3.2            1.6           0.2     1.0
..            ...          ...            ...           ...     ...
120           6.9          3.2            5.7           2.3     3.0
121           5.6          2.8            4.9           2.0     3.0
122           7.7          2.8            6.7           2.0     3.0
123           6.3          2.7            4.9           1.8     3.0
124           6.7          3.3            5.7           2.1     3.0
125           7.2          3.2            6.0           1.8     3.0
126           6.2          2.8            4.8           1.8     3.0
127           6.1          3.0            4.9           1.8     3.0
128           6.4          2.8            5.6           2.1     3.0
129           7.2          3.0            5.8           1.6     3.0
130           7.4          2.8            6.1           1.9     3.0
131           7.9          3.8            6.4           2.0     3.0
132           6.4          2.8            5.6           2.2     3.0
133           6.3          2.8            5.1           1.5     3.0
134           6.1          2.6            5.6           1.4     3.0
135           7.7          3.0            6.1           2.3     3.0
136           6.3          3.4            5.6           2.4     3.0
137           6.4          3.1            5.5           1.8     3.0
138           6.0          3.0            4.8           1.8     3.0
139           6.9          3.1            5.4           2.1     3.0
140           6.7          3.1            5.6           2.4     3.0
141           6.9          3.1            5.1           2.3     3.0
142           5.8          2.7            5.1           1.9     3.0
143           6.8          3.2            5.9           2.3     3.0
144           6.7          3.3            5.7           2.5     3.0
145           6.7          3.0            5.2           2.3     3.0
146           6.3          2.5            5.0           1.9  

In [25]:
data = pd.read_csv("Iris.csv")
data = data[['sepal_length','sepal_width', ' petal_length',' petal_width']]
norm_data = (data - data.min()) / (data.max() - data.min())
    norm_data[' class'] = data[' class']


0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...      
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iri